Blog/Models/Article.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;
using Microsoft.Ajax.Utilities;

namespace Blog.Models
{
    public class Article
    {
        private ICollection<Tag> tags;

        private ICollection<File> files;

        public Article()
        {
            this.tags = new HashSet<Tag>();
            
        }



        public Article(string authorId, string title, string phone, string content,
            string year, int categoryId, double price, string city, int horsePower, string condition, string fueltype)
        {
            this.AuthorId = authorId;
            this.Title = title;
            this.Content = content;
            this.CategoryId = categoryId;
            this.Phone = phone;
            this.Year = year;
            this.Price = price;
            this.FuelType = fueltype;
            this.Condition = condition;
            this.City = city;
            this.HorsePower = horsePower;
            this.CategoryId = categoryId;
            this.tags = new HashSet<Tag>();
            this.files = new List<File>();
            this.DateCreated = DateTime.Now;
        }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }


        public virtual Cars Cars { get; set; }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }


        public virtual ApplicationUser Author { get; set; }


        public bool IsAuthor(string name)
        {
            return this.Author.UserName.Equals(name);
        }

        public virtual ICollection<Tag> Tags
        {
            get { return this.tags; }
            set { this.tags = value; }
        }

        public virtual ICollection<File> Files
        {
            get { return this.files; }
            set { this.files = value; }
        }

        public virtual ICollection<FilePath> FilePaths { get; set; }

        [Required]
        public double Price { get; set; }

        [Required]
        [StringLength(20)]
        public string Phone { get; set; }

        [Required]
        public string Year { get; set; }

        [StringLength(30)]
        public string City { get; set; }

        public int HorsePower { get; set; }

        public DateTime DateCreated { get; set; }

        [StringLength(30)]
        public string Condition { get; set; }
        [StringLength(30)]
        public string FuelType { get; set; }
    }
}

Blog/Models/ArticleViewModel.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.Models
{
    public class ArticleViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public string AuthorId { get; set; }

        public int CategoryId { get; set; }

        public ICollection<Category> Categories { get; set; }
        
        public string Tags { get; set; }

        public byte[] Image { get; set; }

        
        public ICollection<File> Files { get; set; }

        public ICollection<Cars> Carses { get; set; }


        public double Price { get; set; }

        [Required]
        public string Year { get; set; }

        [Required]
        [StringLength(20)]
        public string Phone { get; set; }

        [StringLength(30)]
        public string City { get; set; }

        public int HorsePower { get; set; }

        public DateTime DateCreated { get; set; }

        public string Condition  { get; set; }

        public string FuelType { get; set; }

       

    }
}

Blog/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    public class ArticleController : Controller
    {
        //
        // GET: Article
        public ActionResult Index()
        {
            
            return RedirectToAction("List");
        }

        //
        // GET: Article/List
        public ActionResult List(int? id)
        {
            using (var database = new BlogDbContext())
            {
                //Get articles from database
                var articles = database.Articles
                    .Include(a => a.Author)
                    .Include(a => a.Tags)
                    .Include(a => a.Files)
                    .ToList();
                    
                return View(articles);
            }

        }

        //
        // GET: Article/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .Include(a => a.Tags)
                    .Include(s => s.Files)
                    .SingleOrDefault(s => s.Id == id);


                if (article == null)    
                {
                    return HttpNotFound();
                }

                return View(article);
            }
        }

        //
        // Get: Article/Create
        [Authorize]
        public ActionResult Create()
        {
            using (var database = new BlogDbContext())
            {
                var model = new ArticleViewModel();
                model.Categories = database.Categories
                    .OrderBy(c => c.Name)
                    .ToList();

                return View(model);
            }
        }

        //
        // POST: Article/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleViewModel model, HttpPostedFileBase upload)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }

            using (var database = new BlogDbContext())
            {
                // get author id
                var authorId = database.Users
                    .Where(u => u.UserName == this.User.Identity.Name)
                    .First()
                    .Id;

                // set articles author
                var article = new Article(authorId, model.Title, model.Phone, model.Content, model.Year,
                    model.CategoryId, model.Price, model.City, model.HorsePower, model.Condition, model.FuelType);


                // save article in DB
                this.SetArticleTags(article, model, database);
                
                //uploading photo
                if (upload != null && upload.ContentLength > 0)
                {
                    var avatar = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Avatar,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        avatar.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    article.Files = new List<File> { avatar };
                }

                database.Articles.Add(article);
                database.SaveChanges();

                return RedirectToAction("Index");
            }
            
        }

        //
        // Get: Article/Delete
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                // Get article from database
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .Include(c => c.Category)
                    .Include(c => c.Files)
                    .First();

                if (!IsUserAuthorizedToEdit(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                // Chek if article exists
                if (article == null)
                {
                    return HttpNotFound();
                }

                ViewBag.TagsString = string.Join(", ", article.Tags.Select(t => t.Name));

                // Pass article to view
                return View(article);
            }
        }

        //
        // Post: Article/Delete
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                // Get article from database 
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .Include(c => c.Category)
                    .Include(c => c.Files)
                    .First();

                // Check if article exists
                if (article == null)
                {
                    return HttpNotFound();
                }

                // Delete article from database
                database.Files.Remove(article.Files.First(f => f.FileType == FileType.Avatar));
                database.Articles.Remove(article);
                database.SaveChanges();

                // Redirect to index page
                return RedirectToAction("Index");
            }
        }

        //
        // Get: Article/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                // Get article from database 
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .Include(a => a.Files)
                    .First();
                    
                    
                if (!IsUserAuthorizedToEdit(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                // Check if article exists
                if (article == null)
                {
                    return HttpNotFound();
                }

                // Create the view model
                var model = new ArticleViewModel();
                model.Id = article.Id;
                model.Title = article.Title;
                model.Phone = article.Phone;
                model.Year = article.Year;
                model.Price = article.Price;
                model.Condition = article.Condition;
                model.FuelType = article.FuelType;
                model.City = article.City;
                model.HorsePower = article.HorsePower;
                model.Content = article.Content;
                model.CategoryId = article.CategoryId;
                model.Categories = database.Categories
                    .OrderBy(c => c.Name)
                    .ToList();
                model.Files = article.Files;
                model.Tags = string.Join(", ", article.Tags.Select(t => t.Name));
                // Pass the view model to view
                return View(model);
            }
        }

        //
        // Post: Article/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleViewModel model, HttpPostedFileBase upload)
        {
            // Check if model state is valid
            if (ModelState.IsValid)
            {
                using (var database = new BlogDbContext())
                {
                    // Get article from database 
                    var article = database.Articles
                        .FirstOrDefault(a => a.Id == model.Id);

                    // Set article properties
                    article.Title = model.Title;
                    article.Phone = model.Phone;
                    article.Year = model.Year;
                    article.Price = model.Price;
                    article.City = model.City;
                    article.HorsePower = model.HorsePower;
                    article.Content = model.Content;
                    article.CategoryId = model.CategoryId;
                    article.Files = model.Files;
                    article.Condition = model.Condition;
                    article.FuelType = model.FuelType;

                    this.SetArticleTags(article, model, database);
                    

                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (article.Files.Any(f => f.FileType == FileType.Avatar))
                        {
                            database.Files.Remove(article.Files.First(f => f.FileType == FileType.Avatar));
                        }
                        var avatar = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Avatar,

Blog/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    public class TagController : Controller
    {
        // GET: Tag
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int? id)
        {
            if (id == null)
            {
                throw new System.ArgumentException("Parameter cannot be null", "original");
            }

            using (var database = new BlogDbContext())
            {
                // Get articles from database
                var artices = database.Tags
                    .Include(t => t.Articles.Select(a => a.Tags))
                    .Include(t => t.Articles.Select(a => a.Files))
                    .Include(t => t.Articles.Select(a => a.Author))
                    .FirstOrDefault(t => t.Id == id)
                    .Articles
                    .ToList();
                // Return the view
                return View(artices);
            }
        }
    }
}

Blog/Views/Article/Create.cshtml
@model Blog.Models.ArticleViewModel
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="well">
        <h2>Create Article</h2>

        @using (Html.BeginForm("Create", "Article", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary("Forms in red are required", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(m => m.Title, new {@class = "control-label col-sm-4 text-danger"})
                    <div class="col-sm-4 ">
                        @Html.TextBoxFor(m => m.Title, new {@class = "form-control",
                       placeholder = "E.g. Mercedes S-CLass 320 CDI"})
                       
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Year, new { @class = "control-label col-sm-4 text-danger" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(m => m.Year, new { @class = "form-control",
                       placeholder = "Year of production"
                   })
                    </div>
                </div>
               
                
                <div class="form-group">
                    @Html.LabelFor(m => m.Phone, new { @class = "control-label col-sm-4 text-danger" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control",
                       placeholder = "+359##########"
                   })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Price, new {@class = "control-label col-sm-4"})
                    <div class="col-sm-4">
                        @Html.TextBoxFor(m => m.Price, new {@class = "form-control",
                       placeholder = "Price in BGN"
                   })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.HorsePower, new {@class = "control-label col-sm-4"})
                    <div class="col-sm-4">
                        @Html.TextBoxFor(m => m.HorsePower, new {@class = "form-control",
                       placeholder = "E.g. 110hp"
                   })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.City, new { @class = "control-label col-sm-4" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(m => m.City, new { @class = "form-control",
                       placeholder = "The city where is the car"
                   })
                    </div>
                </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4 text-danger" })
                        <div class="col-sm-4">
                            @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                        </div>
                    </div>

                <div class="form-group">

                    @Html.LabelFor(m => m.Categories, new { @class = "col-sm-4 control-label text-danger" })
                    <div class="dropdown col-sm-4">
                        @Html.DropDownListFor(m => m.CategoryId,
                            new SelectList(Model.Categories, "Id", "Name"),
                            new { @class = "btn btn-info col-sm-12" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Condition, new { @class = " control-label col-sm-4 text-danger" })
                    <div class="dropdown col-sm-4">
                        @Html.DropDownListFor(m => m.Condition,
                        new List<SelectListItem> {
                            new SelectListItem { Value = "New" , Text = "New" },
                            new SelectListItem { Value = "Used" , Text = "Used" },
                            new SelectListItem { Value = "New Import" , Text = "New Import" },
                            new SelectListItem { Value = "For Parts" , Text = "For Parts" }
                        },
                        new { @class = "btn btn-info col-sm-12" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.FuelType, new { @class = " control-label col-sm-4 text-danger" })
                    <div class="dropdown col-sm-4">
                        @Html.DropDownListFor(m => m.FuelType,
                        new List<SelectListItem> {
                            new SelectListItem { Value = "Petrol" , Text = "Petrol" },
                            new SelectListItem { Value = "Diesel" , Text = "Diesel" },
                            new SelectListItem { Value = "Hybrid" , Text = "Hybrid" },
                            new SelectListItem { Value = "Electric" , Text = "Electric" },
                            new SelectListItem { Value = "LPG" , Text = "LPG" },
                        },
                        new { @class = "btn btn-info col-sm-12" })
                    </div>
                </div>
                <span class="form-group">
                        @Html.Label("Picture", new { @class = "control-label col-sm-4 text-danger" })
                        <span class="col-sm-4">
                            <input type="file" id="Avatar" name="upload" />
                        </span>
                    </span>


                    <div class="form-group">
                        @Html.LabelFor(m => m.Tags, new { @class = "control-label col-sm-4 text-danger" })
                        <div class="col-sm-4">
                            @Html.TextBoxFor(m => m.Tags, new { @class = "form-control col-sm-4" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-4">
                            @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </div>
                </div>
        }
    </div>
</div>

Blog/Views/Article/Delete.cshtml
@model Blog.Models.Article

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="well">
        <h2>Delete Article</h2>
        @using (Html.BeginForm("Delete", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @readonly = "readonly", @rows = "7" })
                </div>
            </div>

            <div class="form-group">

                @Html.LabelFor(c => c.Category, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(c => c.Category.Name, new { @class = "form-control", @readonly = "readonly", @rows = "1" })
                </div>
            </div>
           
                
                <div class="form-group">
                    @Html.LabelFor(m => m.Tags, new { @class = "control-label col-sm-4" })
                    <div class="col-sm-4">
                        @Html.TextBox("tagsString", (object)ViewBag.TagsString, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>

            <span>
                    <img src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Avatar).FileId" alt="avatar" width="800px" />
                </span>

                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-4">
                        @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </div>
                </div>
        }
    </div>
</div>

Blog/Views/Article/Details.cshtml
@model Blog.Models.Article

@{
    ViewBag.Title = "Details";
}

<div class="container">

    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/bg_BG/sdk.js#xfbml=1&version=v2.8&appId=1813083162293390";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    <article>
        <header>
            <h2>
                @Model.Title
            </h2>
        </header>
        <div class="col-sm-6">
            <article>
                @if (Model.Files.Any(f => f.FileType == Blog.Models.FileType.Avatar))
            {

                <dd>
                    <img src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Avatar).FileId"
                         alt="avatar" width="500px" />
                   
                </dd>

                }
            </article>
        </div>
        <div style="margin-top: 10px; font-size: 20px" class="text-info">
            <p>
                <span class="glyphicon glyphicon-list-alt"></span> Year of production: @Model.Year
            </p>
            <p>
                <span class="glyphicon glyphicon-stats"></span> Condition: @Model.Condition
            </p>
            <p>
                <span class="glyphicon glyphicon-tint"></span> Fuel: @Model.FuelType
            </p>
            <p>
                <span class="glyphicon glyphicon-flash"></span> Horse Power: @Model.HorsePower
            </p>

            <p>
                <span class="glyphicon glyphicon-home"></span> City: @Model.City
            </p>


            <p>
                <span class="glyphicon glyphicon-usd"></span> Price: <span class="text-danger">@Model.Price лв.</span>
            </p>


            <p>
                <span class="glyphicon glyphicon-user"></span> Contact Person: @Model.Author.FullName
            </p>
            <p>
                <span class="glyphicon glyphicon-earphone"></span> Call: @Model.Phone
            </p>

            <p>
                <span class="glyphicon glyphicon-envelope"></span> E-mail: @Model.Author.Email
            </p>
            <p>
                <span class="glyphicon glyphicon-globe"></span> Published on: @Model.DateCreated
            </p>

        </div>

        <div class="col-sm-12">
            <br />
            <article>
                <div class="pull-left">
                    <span class="glyphicon glyphicon-list-alt" style="color: red"></span>
                    <text style="color: darkblue">Information: @Model.Content</text>
                </div>
            </article>
        </div>
        <div class="fb-share-button" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u&amp;src=sdkpreparse">Споделяне</a></div>

        <footer class="pull-right">
            @if (User.IsInRole("Admin") || Model.IsAuthor(User.Identity.Name))
            {

                @Html.ActionLink("Edit", "Edit", "Article", new { @id = Model.Id }, new { @class = "btn btn-success btn-xs" })
                @Html.ActionLink("Delete", "Delete", "Article", new { @id = Model.Id }, new { @class = "btn btn-danger btn-xs" })
            }

            @Html.ActionLink("Back", "Index", "Article", null, new { @class = "btn btn-default btn-xs" })
        </footer>
    </article>
</div>
<hr />

Blog/Views/Article/List.cshtml
@model List<Blog.Models.Article>
@{
    ViewBag.Title = "List";
}

<div class="container">
    <div class="row">
        @foreach (var article in Model)
        {
            <div class="col-md-3">
                <article>
                    <header>
                        <h4>
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </h4>
                    </header>
                    <p>
                        
                        @if (article.Files.Any(f => f.FileType == FileType.Avatar))
                        {
                            <a class="media-left" href="@Url.Action("Details", "Article", new { id = article.Id })">
                                <img class="media-object" src="~/File?id=@article.Files.First(f => f.FileType == FileType.Avatar).FileId" alt="image" width="180" />
                            </a>
                        }
                        
                    </p>
                    
                    <footer>
                        
                        <div class="pull-left">
                            @foreach (var tag in article.Tags)
                            {
                                @Html.ActionLink(tag.Name, "List", "Tag", new {@id = tag.Id}, new {@class = "btn btn-default btn-xs"})
                            }
                        </div>
                    </footer>
                </article>
            </div>
        }


    </div>
</div>
<hr />